services:
  telegram-dd:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: telegram-download
    read_only: true
    environment:
      - TELEGRAM_DAEMON_API_ID=
      - TELEGRAM_DAEMON_API_HASH=
      - TELEGRAM_DAEMON_CHANNEL=
      - TELEGRAM_DAEMON_DEST=/downloads
      - TELEGRAM_DAEMON_SESSION_PATH=/session
      - TELEGRAM_DAEMON_WORKERS=2
      - TELEGRAM_DAEMON_PROXY_RESOLVE_ONCE=1
      # Proxy configuration (uncomment and modify if needed)
      #- TELEGRAM_DAEMON_PROXY_HOST=x.x.x.x
      #- TELEGRAM_DAEMON_PROXY_PORT=7890
      #- TELEGRAM_DAEMON_PROXY_TYPE=socks5
      # Proxy authentication (uncomment and modify if needed)
      #- TELEGRAM_DAEMON_PROXY_USERNAME=your_username
      #- TELEGRAM_DAEMON_PROXY_PASSWORD=your_password
    ports:
      - 7373:7373
    volumes:
      - ./downloads:/downloads
      - ./sessions:/session
      - ./db:/app/db
    restart: unless-stopped

volumes:
  downloads:
  sessions:
